joinMessage:
  - '&7&m-------------------------------------'
  - ''
  - '&bWelcome back to &9&lThe Official MC Server'
  - ''
  - '&7&o* Website: https://mcserver.com'
  - '&7&o* Discord: https://discord.mcserver.com'
  - ''
  - '&7&m-------------------------------------'